In [1]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('/content/sample_data/iris.data.csv')
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [5]:
data.shape

(149, 5)

In [7]:
data['Iris-setosa'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: Iris-setosa, dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [9]:
data.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [10]:
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [12]:
x = data.iloc[:,0:4]
x.head()

5.1  3.5  1.4  0.2
0  4.9  3.0  1.4  0.2
1  4.7  3.2  1.3  0.2
2  4.6  3.1  1.5  0.2
3  5.0  3.6  1.4  0.2
4  5.4  3.9  1.7  0.4

In [13]:
y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Iris-setosa, dtype: object

Feature Scalling

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
x = scaler.fit_transform(x)
x[0:5]

array([[-1.1483555 , -0.11805969, -1.35396443, -1.32506301],
       [-1.3905423 ,  0.34485856, -1.41098555, -1.32506301],
       [-1.51163569,  0.11339944, -1.29694332, -1.32506301],
       [-1.02726211,  1.27069504, -1.35396443, -1.32506301],
       [-0.54288852,  1.9650724 , -1.18290109, -1.0614657 ]])

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =  train_test_split(x,y, test_size=0.2)

In [18]:
x_train.shape

(119, 4)

In [19]:
x_test.shape

(30, 4)

Train Model

In [20]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [21]:
pred = model.predict(x_test)
pred[0:5]

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [22]:
y_test[0:5]

84     Iris-versicolor
112     Iris-virginica
62     Iris-versicolor
132     Iris-virginica
9          Iris-setosa
Name: Iris-setosa, dtype: object

Check Successability

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[ 8,  0,  0],
       [ 0,  7,  1],
       [ 0,  2, 12]])

In [26]:
result = pd.DataFrame(data=[y_test.values,pred],index=['y_test','pred'])
result.transpose()

y_test             pred
0   Iris-versicolor  Iris-versicolor
1    Iris-virginica   Iris-virginica
2   Iris-versicolor  Iris-versicolor
3    Iris-virginica  Iris-versicolor
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6    Iris-virginica   Iris-virginica
7    Iris-virginica  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11   Iris-virginica   Iris-virginica
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16  Iris-versicolor   Iris-virginica
17   Iris-virginica   Iris-virginica
18      Iris-setosa      Iris-setosa
19  Iris-versicolor  Iris-versicolor
20   Iris-virginica   Iris-virginica
21   Iris-virginica   Iris-virginica
22   Iris-virginica   Iris-virginica
23   Iris-virginica   Iris-virginica
24  Iris-versicolor  Iris-versicolor
25      Iris-setosa      Iris-setosa
26   Iris-virginica   Iris-virginica
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica

Get Suitable K value

In [27]:
correct_sum = []
for i in range(1,20):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  pred = model.predict(x_test)
  correct = np.sum(pred == y_test)
  correct_sum.append(correct)

In [28]:
correct_sum

[27, 27, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 26, 26, 26, 25, 26, 26]

check k value

In [31]:
model = KNeighborsClassifier(n_neighbors=8)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [32]:
accuracy_score(y_test, pred)

0.9666666666666667

In [33]:
confusion_matrix(y_test,pred)

array([[ 8,  0,  0],
       [ 0,  8,  0],
       [ 0,  1, 13]])